### ISSUE TITLE
Possible way of reducing file size

### ISSUE THREAD

**Issue by aidenybai** [Aidunlin/MeanScout#2]
Have a buildtool (such as parcel or some custom nodejs minification build tool)

The Github pages would be served under build/ or have it statically served with netlify.

This can possibly reduce file size due to minification

**Comment by Aidunlin** [comment]
Funny enough, GitHub Pages can't be served specifically within any folder. It has to either be the entire master branch, a branch called "gh-pages", or in a /docs folder within the master branch.

Also, I think 1 megabyte is suitable enough for now. I'd rather keep MeanScout simple like this without having to set up minification build tools. With that being said, if this project massively goes up in scale, I'll use whatever's necessary to keep the app size small.

**Comment by aidenybai** [comment]
Sounds good, hopefully this can be useful in the future - right now it's easily the best lightweight scouting tool for FRC
